---
title: "PAC 2 VISUALITZACIÓ DE DADES"
output: html_notebook
---


```{r}
# Libraries
if (!require(tidyverse)) install.packages('tidyverse', repos='http://cran.us.r-project.org'); library(tidyverse)
if (!require(viridis)) install.packages('viridis', repos='http://cran.us.r-project.org'); library(viridis)
if (!require(patchwork)) install.packages('patchwork', repos='http://cran.us.r-project.org'); library(patchwork)
if (!require(hrbrthemes)) install.packages('hrbrthemes', repos='http://cran.us.r-project.org'); library(hrbrthemes)
if (!require(igraph)) install.packages('igraph', repos='http://cran.us.r-project.org'); library(igraph)
if (!require(ggraph)) install.packages('ggraph', repos='http://cran.us.r-project.org'); library(ggraph)
if (!require(colormap)) install.packages('colormap', repos='http://cran.us.r-project.org'); library(colormap)
if (!require(ggplot2)) install.packages('ggplot2', repos='http://cran.us.r-project.org'); library(ggplot2)
if (!require(dplyr)) install.packages('dplyr', repos='http://cran.us.r-project.org'); library(dplyr)
if (!require(plotly)) install.packages('plotly', repos='http://cran.us.r-project.org'); library(plotly)
if (!require(quantmod)) install.packages('quantmod', repos='http://cran.us.r-project.org'); library(quantmod)
if (!require(tidygraph)) install.packages('tidygraph', repos='http://cran.us.r-project.org'); library(tidygraph)
```
1.- LINE CHART

```{r}
# Crear data frame
vida <- data.frame(any=c(1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000),
                       esp_home=c(46.3, 48.4, 53.6 ,58.1, 60.8, 65.6, 66.6, 67.1, 70, 71.8, 74),
                       esp_dona=c(48.3, 51.8, 54.6, 61.6, 65.2, 71.1, 73.1, 74.7, 77.4, 78.8, 80.1))


# Plot
p0 = ggplot() +
    geom_line(data=vida, aes(x = any, y = esp_home, color = "blue")) +
    geom_line(data=vida, aes(x = any, y = esp_dona, color = "red")) +
    scale_color_manual(name = "Sexe", labels=c("Home", "Dona"), values = c("blue",  "red")) +
    theme_ipsum() +
    xlab('Any') +
    ylab('Esperança de vida en anys') +
    ggtitle("Esperança de vida USA")
```

```{r}
p0
```

2.- ARC DIAGRAM

```{r}
# A really simple edge list
airports <- data.frame(name=c("DFW", "ORD", "LAX", "DEN", "ATL"),
                       label=c("Dallas", "Chicago", "Los Angeles", "Denver", "Atlanta"))

links=data.frame(
    source=c("DFW", "DFW", "DFW", "DFW", "ORD",  "LAX", "DEN","ATL"),
    target=c("ORD", "LAX", "DEN", "ATL", "DFW",  "DFW", "DFW", "DFW"),
    routes=c(20, 19, 20, 17, -20, -19, -18, -20),
    color=c("blue", "blue", "blue", "blue", "red", "red", "red", "red")
    )

```


```{r}
# Make a cord diagram
net.tidy <- tbl_graph(nodes = airports, edges = links, directed = TRUE)

p3 <-  ggraph(net.tidy, layout = "linear") + 
  geom_edge_arc(arrow = arrow(type = "closed", length = unit(3, 'mm')), aes(colour = color, width = abs(routes), label=abs(routes)), 
                alpha = 0.8, start_cap = circle(.1, unit = "native"), end_cap = circle(.1, unit = "native")) + 
  scale_edge_width(range = c(0.2, 2)) +
  geom_node_text(aes(label = label),  repel = FALSE) +
  labs(edge_width = "Numero de rutas") +
  theme_graph()+
  theme(legend.position = "none") +
  labs(caption = paste0('Vols amb origen i destí Dallas '))

```


```{r}
# Make a cord diagram
p3
```

3.- OHLC CHART

```{r}
getSymbols("GOOG",src='yahoo')

df <- data.frame(Date=index(GOOG),coredata(GOOG))
df <- tail(df, 30)

fig <- df %>% plot_ly(x = ~Date, type="ohlc",
          open = ~GOOG.Open, close = ~GOOG.Close,
          high = ~GOOG.High, low = ~GOOG.Low) 
fig <- fig %>% layout(title = "Cotització Google",
         xaxis = list(title="Data", rangeslider = list(visible = F)),
         yaxis = list(title="Cotització ($)", rangeslider = list(visible = F)))


fig
```
